// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKt6LFR_tTjJiG5_rnSOR7CWG0RoPch00',
    appId: '1:570043824343:web:04f61ce3cd93467fbe5892',
    messagingSenderId: '570043824343',
    projectId: 'flipkart-ehr-8593c',
    authDomain: 'flipkart-ehr-8593c.firebaseapp.com',
    storageBucket: 'flipkart-ehr-8593c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlgNRMdojIC6UXzfrmnsns3bSmoKPH9Ho',
    appId: '1:570043824343:android:ef3a5bd3db01cea9be5892',
    messagingSenderId: '570043824343',
    projectId: 'flipkart-ehr-8593c',
    storageBucket: 'flipkart-ehr-8593c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBESB0IIKJt0ln0uSDQpCkYD8jS9Oif4q4',
    appId: '1:570043824343:ios:b6b3c0b86a210b21be5892',
    messagingSenderId: '570043824343',
    projectId: 'flipkart-ehr-8593c',
    storageBucket: 'flipkart-ehr-8593c.appspot.com',
    iosClientId: '570043824343-q2e3hv514hujbeltf74lnkhe1dupu10b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipkartEhr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBESB0IIKJt0ln0uSDQpCkYD8jS9Oif4q4',
    appId: '1:570043824343:ios:300f2bebb4f422d1be5892',
    messagingSenderId: '570043824343',
    projectId: 'flipkart-ehr-8593c',
    storageBucket: 'flipkart-ehr-8593c.appspot.com',
    iosClientId: '570043824343-m31lrmu8vr7h0e0t8dtq1u1v3or6ocpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipkartEhr.RunnerTests',
  );
}
